entity:
  id: ip
  name: IP address
  snapshot: true

attribs:
  activity:
    name: Activity
    description: Number of flows, packets and bytes sent and received by the IP address in a time interval.
    type: timeseries
    timeseries_type: regular
    timeseries_params:
      max_age: 14d
      time_step: 10m
    series:
      in_flows:
        data_type: float
      in_packets:
        data_type: float
      in_bytes:
        data_type: float
      out_flows:
        data_type: float
      out_packets:
        data_type: float
      out_bytes:
        data_type: float

  open_ports:
    name: Open ports
    description: List of open and actively used ports on the device (obtained by observing traffic on that ports).
    type: observations
    data_type: int
    multi_value: true
    confidence: true
    history_force_graph: true
    history_params:
      pre_validity: 8h
      post_validity: 8h
      max_age: 2d
      aggregate: true

  # DNS hostname
  hostname:
    name: Hostname
    description: Hostname associated with the IP address according to a DNS PTR query.
    type: plain
    data_type: string


  # Recog data
  recog_ssh:
    name: Recog - SSH
    description: Information extracted from SSH banners sent by this IP (using Recog pattern database)
    type: observations
    data_type: dict<os?:json,service?:json,hw?:json,openssh?:json>
    multi_value: true
    history_params:
      pre_validity: 24h
      post_validity: 24h
      max_age: 7d
      aggregate: true

  recog_smtp:
    name: Recog - SMTP
    description: Information extracted from SMTP banners sent by this IP (using Recog pattern database)
    type: observations
    data_type: dict<os?:json,service?:json,hw?:json,host?:json>
    multi_value: true
    history_params:
      pre_validity: 24h
      post_validity: 24h
      max_age: 7d
      aggregate: true

  # IP activity classes
  activity_class:
    name: Activity class
    description: Class of the device activity based on the number of transmitted bytes (off, idle, low, medium, high).
    type: plain
    data_type: category<string; off, idle, light, medium, high>

  # DNS open resolver
  open_resolver:
    name: DNS open resolver
    description: Open DNS resolver is running on the device
    type: plain
    data_type: tag
