# Configuration of HistoryManager system, responsible for
# - aggregating datapoints in master records
# - deleting old datapoints from master records
# - deleting old snapshots
# - archiving old datapoints form raw collections

# Aggregation - merging identical value datapoints in master records
aggregation_schedule:
  minute: "*/10"

# Deleting old datapoints from master records
mark_datapoints_schedule:
  hour: "7,19"
  minute: "45"

datapoint_cleaning_schedule:
  minute: "*/20"

# Deleting old snapshots
snapshot_cleaning:
  schedule: {minute: "30"}
  older_than: 14d

# Archiving old datapoints form raw log collection
datapoint_archivation:
  schedule: {hour: 2, minute: 0}
  older_than: 1d
  archive_dir: "/data/datapoints/"
