name: Release

on:
  push:
    tags:
      - "v*" # Run workflow on version tags

jobs:
  release:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set metadata
        run: |
          mkdir ~/.config
          echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          cat << EOF > ~/.config/copr
          ${{ secrets.COPR_CONFIG }}
          EOF
        shell: bash

      # `sqlite` and `sqlite-devel` packages are apparently needed for NodeJS
      # 22.14. Otherwise this symbol lookup error is thrown:
      # ```
      # /usr/bin/node-22: symbol lookup error: /lib64/libnode.so.127: undefined symbol: sqlite3session_attach
      # ```
      # This is a workaround until the issue is resolved. We are not using SQLite in the project.
      - name: Install dependencies
        run: |
          dnf install -y \
            nodejs npm \
            make cmake \
            rpm-build copr-cli \
            sqlite sqlite-devel

      - name: Package ADiCT lite
        run: |
          cd dp3_server
          mkdir build
          cd build
          cmake .. -Dpackage_version=$VERSION
          make package_source
          make package

      - name: Package GUI
        run: |
          cd frontend
          mkdir build
          cd build
          cmake .. -Dpackage_version=$VERSION
          make package_source
          make package

      - name: Package NEMEA modules
        run: |
          cd nemea_modules
          mkdir build
          cd build
          cmake .. -Dpackage_version=$VERSION
          make package_source
          make package

      - name: Create Github release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          generate_release_notes: true
          files: |
            dp3_server/build/*.rpm
            frontend/build/*.rpm
            nemea_modules/build/*.rpm

      - name: Publish packages to COPR
        run: |
          copr build @CESNET/NEMEA-stable \
            dp3_server/build/*.src.rpm \
            frontend/build/*.src.rpm \
            nemea_modules/build/*.src.rpm
