name: Release

on:
  push:
    tags:
      - "v*" # Run workflow on version tags

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set metadata
        run: |
          echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
        shell: bash

      - name: Install dependencies
        run: |
          # Remove existing cmake installation
          # This is needed because full path of `cmake` is embedded
          # (https://gitlab.kitware.com/cmake/cmake/-/commit/611ad194991950ed32189d7314bdbb6cb7cc673b)
          # into generated source RPM packages. Path `/usr/local/bin/cmake`
          # is non-standard and doesn't work outside Github action.
          rm -f /usr/local/bin/cmake

          sudo apt update && sudo apt-get install -y make cmake rpm

      - name: Setup Node and npm
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Package ADiCT lite
        run: |
          cd dp3_server
          mkdir build
          cd build
          cmake .. -Dpackage_version=$VERSION
          make package_source
          make package

      - name: Package GUI
        run: |
          cd frontend
          mkdir build
          cd build
          cmake .. -Dpackage_version=$VERSION
          make package_source
          make package

      - name: Package NEMEA modules
        run: |
          cd nemea_modules
          mkdir build
          cd build
          cmake .. -Dpackage_version=$VERSION
          make package_source
          make package

      - name: Create Github release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          files: |
            dp3_server/build/*.rpm
            frontend/build/*.rpm
            nemea_modules/build/*.rpm
