name: Ruff

on:
  pull_request:
  push:

jobs:
  lint_and_format:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: "0.8.0"

      - name: Run Ruff Linting
        run: ruff check --output-format=github

      - name: Run Ruff Formatting
        run: ruff format --diff
